/**
 * AorticAI Workstation — DOM handle registry
 * Extracted from main.ts (PR #3 shell modularization).
 *
 * Mutable registry populated after renderShellHTML() writes the DOM.
 * Wiring (getElementById → DOM.foo assignments) still lives in main.ts
 * because it depends on many module-level symbols; moving it here would
 * create circular imports. See docs/REFACTOR_LOG.md.
 */
import type { ViewportKey } from '../types';

export const DOM = {
  headerStatus: null as HTMLDivElement | null,
  bootStage: null as HTMLDivElement | null,
  dataSourceBanner: null as HTMLDivElement | null,
  dataQualityGateBanner: null as HTMLDivElement | null,
  dataQualityGateReasons: null as HTMLUListElement | null,
  coronaryReviewBanner: null as HTMLDivElement | null,
  coronaryReviewAcknowledge: null as HTMLButtonElement | null,
  headerCaseInfo: null as HTMLDivElement | null,
  caseInfoLeft: null as HTMLDivElement | null,
  caseInfoCenter: null as HTMLDivElement | null,
  caseInfoRight: null as HTMLDivElement | null,
  gpuStatusDot: null as HTMLSpanElement | null,
  gpuStatusText: null as HTMLSpanElement | null,
  submitCaseButton: null as HTMLButtonElement | null,
  submitCaseModal: null as HTMLDivElement | null,
  submitCaseClose: null as HTMLButtonElement | null,
  annotateOpenButton: null as HTMLButtonElement | null,
  annotatePasswordModal: null as HTMLDivElement | null,
  annotatePasswordClose: null as HTMLButtonElement | null,
  annotatePasswordForm: null as HTMLFormElement | null,
  annotatePasswordInput: null as HTMLInputElement | null,
  annotatePasswordError: null as HTMLDivElement | null,
  annotatePanel: null as HTMLDivElement | null,
  annotatePanelMode: null as HTMLSpanElement | null,
  annotateExitButton: null as HTMLButtonElement | null,
  annotateClearButton: null as HTMLButtonElement | null,
  annotateSaveButton: null as HTMLButtonElement | null,
  annotateSaveStatus: null as HTMLDivElement | null,
  annotateNote: null as HTMLTextAreaElement | null,
  annotateHeightLeft: null as HTMLElement | null,
  annotateHeightRight: null as HTMLElement | null,
  submitCaseForm: null as HTMLFormElement | null,
  submitCaseFile: null as HTMLInputElement | null,
  submitCasePatientId: null as HTMLInputElement | null,
  submitCaseSubmit: null as HTMLButtonElement | null,
  jobProgressBanner: null as HTMLDivElement | null,
  jobProgressFill: null as HTMLDivElement | null,
  jobProgressLabel: null as HTMLSpanElement | null,
  bootOverlay: null as HTMLDivElement | null,
  bootOverlayTitle: null as HTMLHeadingElement | null,
  bootOverlayText: null as HTMLParagraphElement | null,
  bootOverlayDetail: null as HTMLPreElement | null,
  retryLatestButton: null as HTMLButtonElement | null,
  caseMeta: null as HTMLDivElement | null,
  mprStatus: null as HTMLDivElement | null,
  layoutGridButton: null as HTMLButtonElement | null,
  layoutSingleButton: null as HTMLButtonElement | null,
  toolButtons: [] as HTMLButtonElement[],
  windowPreset: null as HTMLSelectElement | null,
  cineToggle: null as HTMLButtonElement | null,
  cineSpeed: null as HTMLSelectElement | null,
  slabMipToggle: null as HTMLButtonElement | null,
  slabThicknessSlider: null as HTMLInputElement | null,
  slabThicknessValue: null as HTMLSpanElement | null,
  slabPresetButtons: [] as HTMLButtonElement[],
  resetViewportButton: null as HTMLButtonElement | null,
  auxMode: null as HTMLSelectElement | null,
  centerlineSlider: null as HTMLInputElement | null,
  centerlineValue: null as HTMLSpanElement | null,
  loadShowcaseButton: null as HTMLAnchorElement | null,
  loadLatestButton: null as HTMLAnchorElement | null,
  reportOpenButton: null as HTMLButtonElement | null,
  focusAnnulusButton: null as HTMLButtonElement | null,
  focusStjButton: null as HTMLButtonElement | null,
  focusRootButton: null as HTMLButtonElement | null,
  focusCoronaryButton: null as HTMLButtonElement | null,
  undoMeasurementButton: null as HTMLButtonElement | null,
  deleteMeasurementButton: null as HTMLButtonElement | null,
  clearMeasurementsButton: null as HTMLButtonElement | null,
  backToCrosshairButton: null as HTMLButtonElement | null,
  localeButtons: [] as HTMLButtonElement[],
  measurementGrid: null as HTMLDivElement | null,
  planningGrid: null as HTMLDivElement | null,
  planningPanelSection: null as HTMLElement | null,
  measurementPanelSection: null as HTMLElement | null,
  planningPanelToggle: null as HTMLButtonElement | null,
  manualReviewToggle: null as HTMLButtonElement | null,
  measurementPanelToggle: null as HTMLButtonElement | null,
  exportMeasurementsCsv: null as HTMLButtonElement | null,
  manualReviewGrid: null as HTMLDivElement | null,
  manualReviewStatus: null as HTMLDivElement | null,
  manualReviewSection: null as HTMLElement | null,
  pearsPanel: null as HTMLDivElement | null,
  qaList: null as HTMLUListElement | null,
  evidenceList: null as HTMLUListElement | null,
  downloadList: null as HTMLDivElement | null,
  acceptanceSummary: null as HTMLDivElement | null,
  acceptanceList: null as HTMLUListElement | null,
  capabilityGrid: null as HTMLDivElement | null,
  caseOverviewSummary: null as HTMLDivElement | null,
  annotationStatus: null as HTMLDivElement | null,
  annotationDetail: null as HTMLDivElement | null,
  annotationButton: null as HTMLButtonElement | null,
  rawBlock: null as HTMLPreElement | null,
  threeStage: null as HTMLDivElement | null,
  threeFallback: null as HTMLDivElement | null,
  landmarkLayerButtons: [] as HTMLButtonElement[],
  planningTabButtons: [] as HTMLButtonElement[],
  threeMeshToggles: [] as HTMLInputElement[],
  threeMeshOpacity: [] as HTMLInputElement[],
  threeLayerToggles: [] as HTMLInputElement[],
  threeScreenshotButton: null as HTMLButtonElement | null,
  reportDrawer: null as HTMLDivElement | null,
  reportCloseButton: null as HTMLButtonElement | null,
  reportDownloadLink: null as HTMLAnchorElement | null,
  reportFrame: null as HTMLDivElement | null,
  reportEmbed: null as HTMLEmbedElement | null,
  keyMeasurementCard: null as HTMLDivElement | null,
  caseInfoCard: null as HTMLDivElement | null,
  whyMattersCard: null as HTMLDivElement | null,
  whyMattersToggle: null as HTMLButtonElement | null,
  whyMattersBody: null as HTMLDivElement | null,
  viewportCardThree: null as HTMLDivElement | null,
  viewportElements: {} as Record<ViewportKey, HTMLDivElement>,
  viewportCards: {} as Record<ViewportKey, HTMLDivElement>,
  viewportBadges: {} as Record<ViewportKey, HTMLDivElement>,
  viewportFooters: {} as Record<ViewportKey, HTMLDivElement>,
  viewportPlaceholders: {} as Record<ViewportKey, HTMLDivElement>,
  statusHu: null as HTMLSpanElement | null,
  statusPosition: null as HTMLSpanElement | null,
};
