export const SCHEMA_REFS = {
  SCCT_TAVI_CT_CONSENSUS: "SCCT_TAVI_CT_CONSENSUS",
  PIE_3MENSIO_AORTIC_VALVE: "PIE_3MENSIO_AORTIC_VALVE",
  GE_TAVI_ANALYSIS: "GE_TAVI_ANALYSIS",
  VMTK_CENTERLINES: "VMTK_CENTERLINES",
  ITK_CORE: "ITK_CORE",
  NNUNET_FRAMEWORK: "NNUNET_FRAMEWORK",
  VSRR_EFFECTIVE_HEIGHT_LIT: "VSRR_EFFECTIVE_HEIGHT_LIT",
  PEARS_EXOVASC_LIT: "PEARS_EXOVASC_LIT",
  IEC_62304: "IEC_62304",
  ISO_14971: "ISO_14971",
  OWASP_ASVS: "OWASP_ASVS",
} as const;

export type SchemaRef = typeof SCHEMA_REFS[keyof typeof SCHEMA_REFS];
