import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import esbuild from 'esbuild';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, '..');

const appEntry = path.join(repoRoot, 'frontend/workstation/src/main.ts');
const workerEntry = path.join(repoRoot, 'frontend/workstation/src/dicomZip.worker.ts');
const cssPath = path.join(repoRoot, 'frontend/workstation/src/styles.css');
const outputPath = path.join(repoRoot, 'src/generated/workstationAssets.ts');

const appBuild = await esbuild.build({
  entryPoints: [appEntry],
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: ['es2022'],
  write: false,
  logLevel: 'silent',
  external: [
    '@cornerstonejs/core',
    '@cornerstonejs/tools',
    '@cornerstonejs/dicom-image-loader',
    '@cornerstonejs/nifti-volume-loader',
  ],
});

const workerBuild = await esbuild.build({
  entryPoints: [workerEntry],
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: ['es2022'],
  write: false,
  logLevel: 'silent',
});

const css = await readFile(cssPath, 'utf8');
const appJs = appBuild.outputFiles[0].text;
const workerJs = workerBuild.outputFiles[0].text;

const moduleSource = `// Auto-generated by scripts/build_workstation.mjs\nexport const WORKSTATION_STYLE_CSS = ${JSON.stringify(css)};\nexport const WORKSTATION_APP_JS = ${JSON.stringify(appJs)};\nexport const WORKSTATION_DICOM_WORKER_JS = ${JSON.stringify(workerJs)};\n`;

await writeFile(outputPath, moduleSource, 'utf8');
console.log(`Generated ${path.relative(repoRoot, outputPath)}`);
